apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
  app: prometheus
 name: prometheus
 namespace: monitor
spec:
  replicas: 1
  selector:
   matchLabels:
     app: prometheus
  template:
   metadata:
    labels:
      app: prometheus
   spec:
    serviceAccountName: prometheus
    containers:
    - name: prometheus
      image: prom/prometheus:v2.1.0
      imagePullPolicy: Always
      ports:
        - containerPort: 9090
          protocol: TCP
      volumeMounts:
        - mountPath: "/etc/prometheus"
          name: config-prometheus
    volumes:
    - name: config-prometheus
      configMap:
       name: prometheus-config
